name: build-deployable
run-name: ${{ startsWith(github.ref, 'refs/tags/') && format('[{0}] [{1}] Building Deployable Artifact', github.ref_name, github.event.head_commit.message || 'no commit message') || 'Building Deployable Artifact' }}
on:
  workflow_run:
    workflows: [build-action]
    types: [completed]
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        default: "test"
        type: choice
        options:
        - dev
        - staging
        - production

jobs:
  check-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Download artifact from build-action
        uses: actions/download-artifact@v4
        with:
          name: package-app-${{github.event.workflow_run.run_number}}
          run-id: ${{github.event.workflow_run.id}}
          path: ./publish

  deploy-dev:
    needs: check-build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: package-app-${{github.event.workflow_run.run_number}}
          run-id: ${{github.event.workflow_run.id}}
      - name: Print
        run: echo "${{ vars.PRINT_STRING_ENV_MSG }}"

  deploy-staging:
    needs: [check-build, deploy-dev]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: package-app-${{github.event.workflow_run.run_number}}
          run-id: ${{github.event.workflow_run.id}}
      - name: Print
        run: echo "${{ vars.PRINT_STRING_ENV_MSG }}"

  deploy-prod:
    needs: [check-build, deploy-staging]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: package-app-${{github.event.workflow_run.run_number}}
          run-id: ${{github.event.workflow_run.id}}
      - name: Print
        run: echo "${{ vars.PRINT_STRING_ENV_MSG }}"